"""add_soft_delete_to_vehicles

Revision ID: 38a57de69f5e
Revises: a59a32d74fe9
Create Date: 2026-02-15 03:35:09.490776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a57de69f5e'
down_revision: Union[str, Sequence[str], None] = 'a59a32d74fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_deleted')
    # ### end Alembic commands ###
