"""add_service_records_table

Revision ID: a59a32d74fe9
Revises: 782551932111
Create Date: 2026-02-15 02:50:56.037626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59a32d74fe9'
down_revision: Union[str, Sequence[str], None] = '782551932111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('description', sa.String(), nullable=False))
    op.add_column('service_records', sa.Column('mileage', sa.Integer(), nullable=False))
    op.add_column('service_records', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('service_records', sa.Column('service_name', sa.String(), nullable=True))
    op.add_column('service_records', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'date')
    op.drop_column('service_records', 'service_name')
    op.drop_column('service_records', 'cost')
    op.drop_column('service_records', 'mileage')
    op.drop_column('service_records', 'description')
    # ### end Alembic commands ###
